name:                haskell-stuff
version:             0.1.0.0
github:              "derelbenkoenig/haskell-stuff"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "derelbenokenig@gmail.com"
copyright:           "2025 Robert Benson"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- MonadRandom
- singletons
- singletons-th
- megaparsec
- parser-combinators
- exinst
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

language: GHC2024

_ignore_exe_modules: &ignore_exe_modules
  when:
    - condition: false
      other-modules:
        - DerpBob
        - BlankLines

library:
  <<: *ignore_exe_modules
  source-dirs: src
  dependencies:
    - base
    - text
    - bytestring
    - containers
    - vector
    - singletons
    - singletons-th
    - exinst
    - megaparsec
    - parser-combinators

executables:
  derpbob:
    <<: *ignore_exe_modules
    other-modules:
      - ArgParser
    source-dirs: src
    main: DerpBob.hs
    dependencies:
      - base
      - containers
      - text
      - MonadRandom
      - parser-combinators

  blanklines:
    <<: *ignore_exe_modules
    other-modules: []
    main: BlankLines.hs
    source-dirs: src
    language: GHC2024

tests:
  dice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dice
