name:                categories
version:             0.1.0.0
github:              "derelbenkoenig/haskell-stuff/categories"
license:             BSD-3-Clause
author:              "Robert Benson"
maintainer:          "derelbenkoenig@gmail.com"
copyright:           "2025 Robert Benson"

language: GHC2024
default-extensions:
  - NoStarIsType

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:  'reading along with "Compiling to Categories" (Conal Elliot 2017)'

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

